### ISSUE TITLE
Feature Request: make restful API

### ISSUE THREAD

**Issue by jjjan** [stamparm/maltrail#108]
Hello, is it possible to make restful API that expose all information that we have on web

**Comment by stamparm** [comment]
Original idea was to make a thick-client architecture. This basically means that the server itself is used only for storing logs and serving them on request, sensor is used only for inspecting traffic and sending logs to the server, while the (thick) client (aka. web browser) is doing all the fancy severity scoring/threat grouping/... So, restful API is currently impossible to do because there is no such data at the server side that you can see inside the web browser - only RAW log entries.

**Comment by jjjan** [comment]
well as ppl talk in #87 we need at least splunk app or a futures that can save all log in one file. and then we can send it to SIEM, and all data that shows on web is important not just ip, port and feeds.
thanks
