### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by p1r473** [stamparm/maltrail#11345]
Hello,
There are 16 invalid domains in this list. They seem to be IP addresses with ports.
```
  [i] Target: https://raw.githubusercontent.com/stamparm/maltrail/master/trails/static/suspicious/pua.txt
  [✓] Status: Retrieval successful
  [i] Received 1624 domains, 16 domains invalid!
      Sample of invalid domains:
      - 159.89.214.31:1081
      - 68.10.46.234:63274
      - 46.219.3.46:6121
      - 80.229.219.2:6121
      - 170.231.122.20:50519
```

**Comment by MikhailKasimov** [comment]
Hello! 

Not clear where this error-message comes from? What are your actions, when you get this message?

Thnx!

**Comment by p1r473** [comment]
Hi, ignore the format of the error message- it comes from the PiHole updater

I am just trying to report you are using invalid domains in what I think should be used as a hosts file
Unless you have other uses for pua.txt, you cannot use things like ```170.231.122.20:50519``` in a hosts file.

**Comment by MikhailKasimov** [comment]
```you are using invalid domains...``` <-- MT simultaneously uses various methods of malware's\pua's: by domain name, and by IP:port connection, because some malware\pua use specific connections: sometimes just domain name, sometimes IP:port + some domain name (you can meet this in ```njrat``` and ```njrat```-based trails: ```nanocore```, ```adwind```, etc), some -- IP:port only. And all these trail should be covered by detection.

I you'are looking for domain-list only, you can meet https://github.com/stamparm/maltrail#blacklist , but this list is based on ```trails/static/malware```, not ```pua```.

I think PiHole should be able parse and ignore IP:port combinations in its settings, if thery are not acceptable by PiHole.

Or, as a variant, MT should also has domain-lists for ```trails/static/malicious``` and ```trails/static/suspious``` sections respectively. @stamparm What is your opinion here?

**Comment by p1r473** [comment]
Yes, PiHole ignore these lines, I am just reporting this in case they snuck in this list by accident.

**Comment by MikhailKasimov** [comment]
OK. Thanks for reporting!
