### ISSUE TITLE
Remove parked domains from `misc/whitelist.txt`?

### ISSUE THREAD

**Issue by PeterDaveHello** [stamparm/maltrail#19058]
As there's `trails/static/suspicious/parking_site.txt` that marked parking site suspicious, and those whitelisted parking domain can be used for some bad purpose in the future, I wonder if they should just been removed from the whitelist?

I've done the same thing here: https://github.com/nextdns/metadata/pull/949, and now also working on checking the parked domains in the whitelist here, which would be done soon, do you think that I can just send a pull request to remove them here? Thanks.

**Comment by stamparm** [comment]
Sorry, I don't understand what's the issue here. Those IPs inside the `parking_site` are not whitelisted nor used for whitelisting.

**Comment by PeterDaveHello** [comment]
Oh, sorry for ths misleading, I mean to remove some parked domains in `misc/whitelist.txt`, and `suspicious/parking_site` give one more reason that parking domain has its risks, that shouldn't been whitelisted in the `misc/whitelist.txt`, what do you think?

**Comment by stamparm** [comment]
can you please write some examples?

**Comment by PeterDaveHello** [comment]
@stamparm Sure! Here are some examples:

- `justproxy.io`
- `solid.net`
- `100card000office.jp.tn`
- `artbetting.de`
- `emailbasura.org`

**Comment by stamparm** [comment]
ok. i still don't get it :)

for example, `justproxy.io` is parked at `185.53.177.11`, while that same IP is inside the `parking_site.txt`

so, that same site is not whitelisted as you claim

**Comment by PeterDaveHello** [comment]
Oh, okay, I got it, sorry about didn't fully understand the logic.

So woundn't directly remove those parked domains in the whitelist help? Maybe sometimes their IP  is just missed?

**Comment by PeterDaveHello** [comment]
@stamparm @MikhailKasimov tried my best to filter out those parking domains in `whitelist.txt` but not in the `parking_site.txt` and sent those PRs. Do you guys have some new ideas that maybe we can just comment out those parking domains in the white list?

**Comment by stamparm** [comment]
IMHO, this doesn't look like something worth spending time on

**Comment by MikhailKasimov** [comment]
The most interesting case was with ```wordbot.xyz``` domain: initially it was marked as being malware, then was moved to whitelist, because his owner said, that domain clean is, and now ```wordbot.xyz``` is again ownerless and potentially could be used by crooks... And, after some time, it again would be bought by someome for white goals... Generally, MT has many generic trails, that allow to detect malicious traffic. So, there is always a chance, that some new malicious traffic gonna get detected by generic heur signs. And ping-ponging such domains to-and-from whitelist looks as making noise.

BTW, just if it is interesting -- take a look on Example 2 of this wiki-page: https://github.com/stamparm/maltrail/wiki/Maltrail-detection-nuances . Hope, you'll see here a mechanism, that allows to detect malicious traffic, even if domain is legit itself.

Hope, this works for you. :)
