### ISSUE TITLE
Fedora Installation guide

### ISSUE THREAD

**Issue by matheus1760** [stamparm/maltrail#19072]
It would be good to have a _specific_ section of how to install the **mailtrail** in the **RHEL** systems, like fedora

**Comment by MikhailKasimov** [comment]
Hello!

Some time ago I wrote algo for CentOS: https://community.nethserver.org/t/maltrail-addon-as-a-possible-new-feature/14552/5 , but generally it had no specific RHEL-based nuances, except installation of ```epel-release```.

So, I suppose, on Fedora everything gonna installed OK with algo, described for ```(open)SUSE``` distro section, but with using ```yum install``` of ```dnf install``` instead of ```zypper install```.

Please, check. If something goes incorrect, let us know, please. Thnx!
