### ISSUE TITLE
Matrail Large scale (support)

### ISSUE THREAD

**Issue by conexioninversa** [stamparm/maltrail#19089]
Hi Mikhail,
I'm thinking of installing Maltrail (server) on a large scale (I already told you I'm a big fan), could you tell me some minimum requirements on the server to obtain records from about 350 sensors?
I also have quite a few cobaltStrike malicious domain sources (from my research and honeypots) and would like to collaborate with the sources (trails) so that you have them available on Maltrail. How can I collaborate with you?
Thank you

**Comment by MikhailKasimov** [comment]
Hello!

1) There're no special reqs (CPU/mem/disk capacity/network/etc) for MT's server part, because it is just a collector/visualizator. So you can use standard reqs, that are acceptable to any Linux machine you use.

To be sure, that everything goes OK, I propose to connect 10-15 sensor per day with constant monitoring of server's productivity. Hope, this sound OK for you.

2) Use can put pull-req for ```cobaltstrike-1.txt``` trail-base.

**Comment by MikhailKasimov** [comment]
Do I understand it correctly, that ```I also have quite a few cobaltStrike malicious domain sources (from my research and honeypots) and would like to collaborate with the sources (trails) so that you have them available on Maltrail.``` means this list to parse? --> https://github.com/conexioninversa/C2Intel/blob/main/C2Domain.csv

**Comment by conexioninversa** [comment]
Yes. they are 100% malicious domains

**Comment by MikhailKasimov** [comment]
OK, will try to deal with list today in the evening.
