### ISSUE TITLE
[Questions and Support] In short it works like normal host block list ?

### ISSUE THREAD

**Issue by HakaishinShwet** [stamparm/maltrail#19270]
**Question**
Like we can create hosts file in servers/systems to block particular website/traffic which can prevent particular sites from been accessed by it. So does this project work similarly like that or are there some major or minor differences?

**Comment by MikhailKasimov** [comment]
Hello!

Generally Maltrail does not block anything because of beind intrusion detection system (IDS).

Blocking mechanism are done via ipset/iptables ([1] https://github.com/stamparm/maltrail/wiki/Miscellaneous#1-setting-up-maltrail-as-an-intrusion-prevention-system-ips and [2] https://github.com/stamparm/maltrail/pull/19230) and fail2ban (https://github.com/stamparm/maltrail/issues/19263).

Maltrail works on a) lists (feeds and static) b) heur-based mechanisms, that allow to catch cases of RCE attempts, PHP/SQL-injections, etc.

Similarity to what you are talkin about  is based on point a): lists. Types of lists: feeds, static (Maltrail's ones) and custom (user-defined list for detection).

Details:

https://github.com/stamparm/maltrail/wiki/Maltrail-trails-structure
https://github.com/stamparm/maltrail/wiki/Maltrail-trails-base-format

Hope, I'm full on info to provide.

**Comment by HakaishinShwet** [comment]
thanks for providing proper info on this :-))
